version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./library_back
    volumes:
      # - .:/code
      - ./library_back:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  # front_service:
  #     container_name: frontend
  #     build: ./library_front
  #     volumes:
  #       - ./library_front:/frontend
  #       - /frontend/node_modules
  #     stdin_open: true
  #     environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     command: ["npm", "start"]
  #     ports:
  #       - "3000:3000"
  #     depends_on:
  #       - web

  front_service:
    container_name: front_service
    build: ./library_front
    volumes:
      - './library_front/:/frontend'
      - '/frontend/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    depends_on:
      - web

  nginx:
    image: nginx
    restart: always
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80

  # nginx:
  #   build: ./nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   links:
  #     - "web"
  #     - "db"
  #     - "front_service"